services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=upload
    volumes:
      - './docker:/docker-entrypoint-initdb.d'